### ISSUE TITLE
Run the project

### ISSUE THREAD

**Issue by sanket0354** [PiotrNowicki/emf-and-jta#1]
May i know how to run the project ? 
On JBoss server or something ?

**Comment by PiotrNowicki** [comment]
Hi Sanket,

Yes, the maven will build you a WAR which is then deployable on Java EE app server like JBoss Wildfly, Oracle Glassfish or Apache TomEE.

**Comment by sanket0354** [comment]
Perfect, i want it to work with glassfish. Hopefully it works. Do you suggest any version of glassfish particular to the code ? 

And will it be fine if i ask you further questions/problems if any regarding this ?

**Comment by PiotrNowicki** [comment]
Well, I believe any version that implements EE 6.0 - you can check it on Glassfish website. 

And I actually checked the code - it uses some default datasource that is in JBoss Wildfly server. In Glassfish I am not sure if there is a default one but check the documentation and adjust persistence.xml accordingly if you want to to deploy it on GF.
